CREATE TABLE PROPOSAL_PERSON_NOTIFICATION(
PROPOSAL_NUMBER VARCHAR2(12) NOT NULL ENABLE,
PROP_PERSON_NUMBER NUMBER(12,0) NOT NULL ENABLE,
NOTIFIED_TIME  DATE,
NOTIFICATION_SENDER  VARCHAR2(60),
UPDATE_TIMESTAMP  DATE NOT NULL ENABLE,
UPDATE_USER  VARCHAR2(60),
VER_NBR  NUMBER(8,0) NOT NULL ENABLE,
OBJ_ID  VARCHAR2(36),
CONSTRAINT PK_PROP_NOTIFICATION PRIMARY KEY (PROPOSAL_NUMBER,PROP_PERSON_NUMBER),
CONSTRAINT FK_PROP__NOTIFICATION FOREIGN KEY (PROPOSAL_NUMBER,PROP_PERSON_NUMBER)
REFERENCES EPS_PROP_PERSON (PROPOSAL_NUMBER,PROP_PERSON_NUMBER)
)
/
