INSERT INTO AWARD_REP_TERMS_RECNT(AWARD_REP_TERMS_RECNT_ID,CONTACT_ID,AWARD_REPORT_TERMS_ID,CONTACT_TYPE_CODE,ROLODEX_ID,NUMBER_OF_COPIES,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
SELECT SEQ_AWARD_REP_TERMS_RECNT_ID.NEXTVAL,NULL,Ta.AWARD_REPORT_TERMS_ID,T.CONTACT_TYPE_CODE,T.ROLODEX_ID,T.NUMBER_OF_COPIES,T.VER_NBR,T.UPDATE_TIMESTAMP,T.UPDATE_USER,T.OBJ_ID 
FROM  TEMP_AWARD_REPORT_RCNT T INNER JOIN TEMP_AWARD_REPORT Ta
ON T.AWARD_NUMBER=Ta.AWARD_NUMBER AND T.SEQUENCE_NUMBER=Ta.SEQUENCE_NUMBER AND T.REPORT_CLASS_CODE=Ta.REPORT_CLASS_CODE
AND T.FREQUENCY_CODE=Ta.FREQUENCY_CODE
AND T.FREQUENCY_BASE_CODE=Ta.FREQUENCY_BASE_CODE
AND T.OSP_DISTRIBUTION_CODE=Ta.OSP_DISTRIBUTION_CODE
/
commit
/