select ' Start time of AWARD_REPORT_TERMS,AWARD_REP_TERMS_RECNT script is '|| localtimestamp from dual
/

DECLARE
li_cust_id NUMBER(12,0);
ls_award_number varchar2(40);
li_award_reports_id NUMBER(12,0);
li_seq number(4,0);
li_count number;
ls_distribution_code VARCHAR2(3);
CURSOR c_award_comment IS
SELECT a.AWARD_NUMBER,a.SEQUENCE_NUMBER  Kuali_sequence_number,a.AWARD_ID,ac.MIT_AWARD_NUMBER,ac.SEQUENCE_NUMBER,ac.REPORT_CLASS_CODE,ac.REPORT_CODE,ac.FREQUENCY_CODE,ac.FREQUENCY_BASE_CODE,ac.OSP_DISTRIBUTION_CODE,ac.CONTACT_TYPE_CODE,ac.ROLODEX_ID,ac.DUE_DATE,ac.NUMBER_OF_COPIES,ac.UPDATE_TIMESTAMP,ac.UPDATE_USER FROM AWARD a INNER JOIN TEMP_TAB_TO_SYNC_AWARD t ON a.AWARD_NUMBER=replace(t.MIT_AWARD_NUMBER,'-','-00') AND a.SEQUENCE_NUMBER=t.SEQUENCE_NUMBER
LEFT OUTER JOIN OSP$AWARD_REPORT_TERMS@coeus.kuali ac ON t.MIT_AWARD_NUMBER=ac.MIT_AWARD_NUMBER and t.SEQUENCE_NUMBER=ac.SEQUENCE_NUMBER
WHERE t.FEED_TYPE='N'
ORDER BY a.AWARD_NUMBER,a.SEQUENCE_NUMBER;
r_award_comment c_award_comment%ROWTYPE;

BEGIN
IF c_award_comment%ISOPEN THEN
CLOSE c_award_comment;
END IF;
OPEN c_award_comment;
LOOP
FETCH c_award_comment INTO r_award_comment;
EXIT WHEN c_award_comment%NOTFOUND;
 li_seq:=r_award_comment.Kuali_sequence_number;
 select count(OSP_DISTRIBUTION_CODE) into li_count FROM DISTRIBUTION WHERE OSP_DISTRIBUTION_CODE=r_award_comment.OSP_DISTRIBUTION_CODE;
  IF li_count=0 THEN
    ls_distribution_code:=-1;
	ELSE
	  ls_distribution_code:=r_award_comment.OSP_DISTRIBUTION_CODE;
  END IF;
  IF li_seq=1 THEN
	 li_seq:=li_seq + 1;
  END IF;
 select SEQUENCE_AWARD_ID.NEXTVAL into li_award_reports_id from dual;

    IF r_award_comment.MIT_AWARD_NUMBER IS NULL THEN
	
	     IF ls_award_number is null THEN
		 
		     	
		 
	
	         INSERT INTO AWARD_REPORT_TERMS(AWARD_REPORT_TERMS_ID,AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,REPORT_CLASS_CODE,REPORT_CODE,FREQUENCY_CODE,FREQUENCY_BASE_CODE,OSP_DISTRIBUTION_CODE,DUE_DATE,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
	         SELECT li_award_reports_id,r_award_comment.AWARD_ID,r_award_comment.AWARD_NUMBER,r_award_comment.Kuali_sequence_number,REPORT_CLASS_CODE,REPORT_CODE,FREQUENCY_CODE,FREQUENCY_BASE_CODE,ls_distribution_code,DUE_DATE,1,UPDATE_TIMESTAMP,UPDATE_USER,SYS_GUID() FROM AWARD_REPORT_TERMS
           WHERE AWARD_NUMBER=r_award_comment.AWARD_NUMBER and 	SEQUENCE_NUMBER=(SELECT MAX(aw.SEQUENCE_NUMBER) FROM AWARD_REPORT_TERMS aw where aw.AWARD_NUMBER=r_award_comment.AWARD_NUMBER AND aw.SEQUENCE_NUMBER<li_seq);
       
	         INSERT INTO AWARD_REP_TERMS_RECNT(AWARD_REP_TERMS_RECNT_ID,CONTACT_ID,AWARD_REPORT_TERMS_ID,CONTACT_TYPE_CODE,ROLODEX_ID,NUMBER_OF_COPIES,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
           SELECT SEQ_AWARD_REP_TERMS_RECNT_ID.NEXTVAL,null,li_award_reports_id,CONTACT_TYPE_CODE,ROLODEX_ID,NUMBER_OF_COPIES,1,UPDATE_TIMESTAMP,UPDATE_USER,SYS_GUID() FROM AWARD_REP_TERMS_RECNT
           WHERE AWARD_REPORT_TERMS_ID=(SELECT AWARD_REPORT_TERMS_ID FROM AWARD_REPORT_TERMS WHERE AWARD_NUMBER=r_award_comment.AWARD_NUMBER and 	SEQUENCE_NUMBER=(SELECT MAX(aw.SEQUENCE_NUMBER) FROM AWARD_REPORT_TERMS aw where aw.AWARD_NUMBER=r_award_comment.AWARD_NUMBER AND aw.SEQUENCE_NUMBER<li_seq)); 
           ls_award_number:=r_award_comment.AWARD_NUMBER||r_award_comment.SEQUENCE_NUMBER;
		   
		 ELSIF ls_award_number<>r_award_comment.AWARD_NUMBER||r_award_comment.SEQUENCE_NUMBER THEN
		 
		       INSERT INTO AWARD_REPORT_TERMS(AWARD_REPORT_TERMS_ID,AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,REPORT_CLASS_CODE,REPORT_CODE,FREQUENCY_CODE,FREQUENCY_BASE_CODE,OSP_DISTRIBUTION_CODE,DUE_DATE,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
	         SELECT li_award_reports_id,r_award_comment.AWARD_ID,r_award_comment.AWARD_NUMBER,r_award_comment.Kuali_sequence_number,REPORT_CLASS_CODE,REPORT_CODE,FREQUENCY_CODE,FREQUENCY_BASE_CODE,ls_distribution_code,DUE_DATE,1,UPDATE_TIMESTAMP,UPDATE_USER,SYS_GUID() FROM AWARD_REPORT_TERMS
           WHERE AWARD_NUMBER=r_award_comment.AWARD_NUMBER and 	SEQUENCE_NUMBER=(SELECT MAX(aw.SEQUENCE_NUMBER) FROM AWARD_REPORT_TERMS aw where aw.AWARD_NUMBER=r_award_comment.AWARD_NUMBER AND aw.SEQUENCE_NUMBER<r_award_comment.Kuali_sequence_number);
       
	         INSERT INTO AWARD_REP_TERMS_RECNT(AWARD_REP_TERMS_RECNT_ID,CONTACT_ID,AWARD_REPORT_TERMS_ID,CONTACT_TYPE_CODE,ROLODEX_ID,NUMBER_OF_COPIES,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
           SELECT SEQ_AWARD_REP_TERMS_RECNT_ID.NEXTVAL,null,li_award_reports_id,CONTACT_TYPE_CODE,ROLODEX_ID,NUMBER_OF_COPIES,1,UPDATE_TIMESTAMP,UPDATE_USER,SYS_GUID() FROM AWARD_REP_TERMS_RECNT
           WHERE AWARD_REPORT_TERMS_ID=(SELECT AWARD_REPORT_TERMS_ID FROM AWARD_REPORT_TERMS WHERE AWARD_NUMBER=r_award_comment.AWARD_NUMBER and 	SEQUENCE_NUMBER=(SELECT MAX(aw.SEQUENCE_NUMBER) FROM AWARD_REPORT_TERMS aw where aw.AWARD_NUMBER=r_award_comment.AWARD_NUMBER AND aw.SEQUENCE_NUMBER<li_seq)); 
           ls_award_number:=r_award_comment.AWARD_NUMBER||r_award_comment.SEQUENCE_NUMBER;
		   
		 END IF;  
	   ELSE
	

       INSERT INTO AWARD_REPORT_TERMS(AWARD_REPORT_TERMS_ID,AWARD_ID,AWARD_NUMBER,SEQUENCE_NUMBER,REPORT_CLASS_CODE,REPORT_CODE,FREQUENCY_CODE,FREQUENCY_BASE_CODE,OSP_DISTRIBUTION_CODE,DUE_DATE,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID)
	   VALUES(li_award_reports_id,r_award_comment.AWARD_ID,r_award_comment.AWARD_NUMBER,r_award_comment.Kuali_sequence_number,r_award_comment.REPORT_CLASS_CODE,r_award_comment.REPORT_CODE,r_award_comment.FREQUENCY_CODE,r_award_comment.FREQUENCY_BASE_CODE,ls_distribution_code,r_award_comment.DUE_DATE,1,r_award_comment.UPDATE_TIMESTAMP,r_award_comment.UPDATE_USER,SYS_GUID());
	   
	   INSERT INTO AWARD_REP_TERMS_RECNT(AWARD_REP_TERMS_RECNT_ID,CONTACT_ID,AWARD_REPORT_TERMS_ID,CONTACT_TYPE_CODE,ROLODEX_ID,NUMBER_OF_COPIES,VER_NBR,UPDATE_TIMESTAMP,UPDATE_USER,OBJ_ID) 
       VALUES(SEQ_AWARD_REP_TERMS_RECNT_ID.NEXTVAL,null,li_award_reports_id,r_award_comment.CONTACT_TYPE_CODE,r_award_comment.ROLODEX_ID,r_award_comment.NUMBER_OF_COPIES,1,r_award_comment.UPDATE_TIMESTAMP,r_award_comment.UPDATE_USER,SYS_GUID());
	END IF;	
	
END LOOP;
CLOSE c_award_comment;
END;
/	

select ' End time of AWARD_REPORT_TERMS,AWARD_REP_TERMS_RECNT is '|| localtimestamp from dual
/