select ' Start time of Insert to PROPOSAL_ADMIN_DETAILS is '|| localtimestamp from dual
/
INSERT INTO PROPOSAL_ADMIN_DETAILS(PROPOSAL_ADMIN_DETAIL_ID,DEV_PROPOSAL_NUMBER,INST_PROPOSAL_ID,DATE_SUBMITTED_BY_DEPT,DATE_RETURNED_TO_DEPT,DATE_APPROVED_BY_OSP,DATE_SUBMITTED_TO_AGENCY,INST_PROP_CREATE_DATE,INST_PROP_CREATE_USER,SIGNED_BY,SUBMISSION_TYPE,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
SELECT SEQ_PROPOSAL_ADMIN_DETAILS_ID.NEXTVAL,to_number(pa.DEV_PROPOSAL_NUMBER),p.proposal_id,pa.DATE_SUBMITTED_BY_DEPT,pa.DATE_RETURNED_TO_DEPT,
pa.DATE_APPROVED_BY_OSP,pa.DATE_SUBMITTED_TO_AGENCY,pa.INST_PROP_CREATE_DATE,pa.INST_PROP_CREATE_USER,pa.SIGNED_BY,pa.SUBMISSION_TYPE,
p.update_timestamp,p.update_user,1,SYS_GUID()
FROM OSP$PROPOSAL_ADMIN_DETAILS@coeus.kuali pa,PROPOSAL p,temp_tab_to_sync_ip temp 
where pa.INST_PROPOSAL_NUMBER = p.proposal_number
AND pa.INST_PROP_SEQUENCE_NUMBER = p.sequence_number
AND temp.proposal_number = p.proposal_number
AND temp.sequence_number = p.sequence_number
AND temp.FEED_TYPE='N';

commit;
/
select ' End time of  Insert to PROPOSAL_ADMIN_DETAILS is '|| localtimestamp from dual
/