select ' Start time of UPDATE_AWARD_AMT_FNA_DISTRIBUTION is '|| localtimestamp from dual
/
DECLARE
li_ver_nbr NUMBER(8):=1;
li_amt_info_id NUMBER(12);
li_award_id NUMBER(22);
ls_tnm_document_number VARCHAR2(40 );
li_transaction_detail NUMBER(10,0);
li_transaction NUMBER(10,0):=null;
ls_comments VARCHAR2(2000);
ls_source_award VARCHAR2(12);
ls_processed_flag CHAR(1);
li_commit_count number:=0;
ls_transaction_detail_type	VARCHAR2(12):='PRIMARY';
ls_trans_det_comment VARCHAR2(200 BYTE):='Initial Time And Money creation transaction';
ls2_transaction_detail_type	VARCHAR2(12):='INTERMEDIATE';
ls2_trans_det_comment VARCHAR2(200 BYTE):='Single Node Money Transaction';
li_originating_award_version NUMBER(4):=NULL;
ls_award_number VARCHAR2(12);
li_seq_info NUMBER(4);
ls_mit_awd_number varchar2(12);
li_mit_seq NUMBER(4);

CURSOR c_fna_upd IS
SELECT SEQ_AWARD_AMT_FNA_DSTRBTN_ID.NEXTVAL,a.AWARD_ID,replace(ad.MIT_AWARD_NUMBER,'-','-00')AWARD_NUMBER,ad.SEQUENCE_NUMBER,ad.AMOUNT_SEQUENCE_NUMBER,ad.BUDGET_PERIOD,ad.START_DATE,ad.END_DATE,ad.DIRECT_COST,
ad.INDIRECT_COST,ad.UPDATE_TIMESTAMP,ad.UPDATE_USER,1,null AWARD_AMOUNT_INFO_ID,SYS_GUID() FROM OSP$AWARD_AMT_FNA_DISTRIBUTION ad
 inner join AWARD a on  a.AWARD_NUMBER = replace(ad.MIT_AWARD_NUMBER,'-','-00') and a.SEQUENCE_NUMBER=ad.SEQUENCE_NUMBER
INNER JOIN TEMP_TAB_TO_SYNC_AWARD t ON ad.MIT_AWARD_NUMBER=t.MIT_AWARD_NUMBER AND ad.SEQUENCE_NUMBER=t.SEQUENCE_NUMBER
WHERE t.FEED_TYPE='C';
r_fna_upd c_fna_upd%ROWTYPE;

BEGIN
IF c_fna_upd%ISOPEN THEN
CLOSE c_fna_upd;
END IF;
OPEN c_fna_upd;
LOOP
FETCH c_fna_upd INTO r_fna_upd;
EXIT WHEN c_fna_upd%NOTFOUND;


UPDATE AWARD_AMT_FNA_DISTRIBUTION
SET AMOUNT_SEQUENCE_NUMBER=r_fna_upd.AMOUNT_SEQUENCE_NUMBER,
BUDGET_PERIOD=r_fna_upd.BUDGET_PERIOD,
START_DATE=r_fna_upd.START_DATE,
END_DATE=r_fna_upd.END_DATE,
DIRECT_COST=r_fna_upd.DIRECT_COST,
INDIRECT_COST=r_fna_upd.INDIRECT_COST,
UPDATE_TIMESTAMP=r_fna_upd.UPDATE_TIMESTAMP,
UPDATE_USER=r_fna_upd.UPDATE_USER
WHERE AWARD_NUMBER=r_fna_upd.AWARD_NUMBER
AND SEQUENCE_NUMBER=r_fna_upd.SEQUENCE_NUMBER
AND AMOUNT_SEQUENCE_NUMBER=r_fna_upd.AMOUNT_SEQUENCE_NUMBER
AND BUDGET_PERIOD=r_fna_upd.BUDGET_PERIOD;

END LOOP;
CLOSE c_fna_upd;
END;
/
DELETE FROM AWARD_PERSON_CREDIT_SPLITS WHERE AWARD_PERSON_ID IN (SELECT AWARD_PERSON_ID FROM AWARD_PERSON_CREDIT_SPLITS WHERE AWARD_PERSON_ID NOT IN(SELECT AWARD_PERSON_ID FROM AWARD_PERSONS))
/
DELETE FROM AWARD_PERS_UNIT_CRED_SPLITS WHERE AWARD_PERSON_UNIT_ID IN (SELECT AWARD_PERSON_UNIT_ID FROM AWARD_PERSON_UNITS WHERE AWARD_PERSON_ID NOT IN(SELECT AWARD_PERSON_ID FROM AWARD_PERSONS))
/
DELETE FROM AWARD_PERSON_UNITS WHERE AWARD_PERSON_ID IN (SELECT AWARD_PERSON_ID FROM AWARD_PERSON_UNITS WHERE AWARD_PERSON_ID NOT IN(SELECT AWARD_PERSON_ID FROM AWARD_PERSONS))
/
ALTER TABLE AWARD_PERSON_UNITS ENABLE  CONSTRAINT FK_APU_AW_PERSON
/
ALTER TABLE AWARD_PERSON_CREDIT_SPLITS ENABLE CONSTRAINT FK_AP_CREDIT_SPLIT_AP
/
select ' End time of UPDATE_AWARD_AMT_FNA_DISTRIBUTION is '|| localtimestamp from dual
/