select ' Start time of UPDATE_AWARD_AMOUNT_INFO is '|| localtimestamp from dual
/
DECLARE
li_ver_nbr NUMBER(8):=1;
li_amt_info_id NUMBER(12);
li_award_id NUMBER(22);
ls_tnm_document_number VARCHAR2(40 );
li_transaction_detail NUMBER(10,0);
li_transaction NUMBER(10,0):=null;
ls_comments VARCHAR2(2000);
ls_source_award VARCHAR2(12);
ls_processed_flag CHAR(1);
li_commit_count number:=0;
ls_transaction_detail_type	VARCHAR2(12):='PRIMARY';
ls_trans_det_comment VARCHAR2(200 BYTE):='Initial Time And Money creation transaction';
ls2_transaction_detail_type	VARCHAR2(12):='INTERMEDIATE';
ls2_trans_det_comment VARCHAR2(200 BYTE):='Single Node Money Transaction';
li_originating_award_version NUMBER(4):=NULL;
ls_award_number VARCHAR2(12);
li_seq_info NUMBER(4);
ls_mit_awd_number varchar2(12);
li_mit_seq NUMBER(4);

CURSOR c_amount_upd IS
SELECT a.MIT_AWARD_NUMBER,a.SEQUENCE_NUMBER,a.AMOUNT_SEQUENCE_NUMBER,a.ANTICIPATED_TOTAL_AMOUNT,a.ANT_DISTRIBUTABLE_AMOUNT,a.FINAL_EXPIRATION_DATE,a.CURRENT_FUND_EFFECTIVE_DATE,a.AMOUNT_OBLIGATED_TO_DATE,a.OBLI_DISTRIBUTABLE_AMOUNT,a.OBLIGATION_EXPIRATION_DATE,a.TRANSACTION_ID,a.ENTRY_TYPE,a.EOM_PROCESS_FLAG,a.UPDATE_TIMESTAMP,a.UPDATE_USER,a.ANTICIPATED_CHANGE,a.OBLIGATED_CHANGE,a.OBLIGATED_CHANGE_DIRECT,a.OBLIGATED_CHANGE_INDIRECT,a.ANTICIPATED_CHANGE_DIRECT,a.ANTICIPATED_CHANGE_INDIRECT,a.ANTICIPATED_TOTAL_DIRECT,a.ANTICIPATED_TOTAL_INDIRECT,a.OBLIGATED_TOTAL_DIRECT,a.OBLIGATED_TOTAL_INDIRECT 
FROM OSP$AWARD_AMOUNT_INFO a 
INNER JOIN TEMP_TAB_TO_SYNC_AWARD t ON a.MIT_AWARD_NUMBER=t.MIT_AWARD_NUMBER AND a.SEQUENCE_NUMBER=t.SEQUENCE_NUMBER
WHERE t.FEED_TYPE='C';
r_amount_upd c_amount_upd%ROWTYPE;

BEGIN
IF c_amount_upd%ISOPEN THEN
CLOSE c_amount_upd;
END IF;
OPEN c_amount_upd;
LOOP
FETCH c_amount_upd INTO r_amount_upd;
EXIT WHEN c_amount_upd%NOTFOUND;
SELECT replace(r_amount_upd.MIT_AWARD_NUMBER,'-','-00') INTO ls_award_number FROM DUAL;

UPDATE TRANSACTION_DETAILS
SET OBLIGATED_AMOUNT=r_amount_upd.OBLIGATED_CHANGE,
ANTICIPATED_AMOUNT=r_amount_upd.ANTICIPATED_CHANGE,
UPDATE_TIMESTAMP=r_amount_upd.UPDATE_TIMESTAMP,
UPDATE_USER=r_amount_upd.UPDATE_USER,
OBLIGATED_DIRECT_AMOUNT=r_amount_upd.OBLIGATED_CHANGE_DIRECT,
OBLIGATED_INDIRECT_AMOUNT=r_amount_upd.OBLIGATED_CHANGE_INDIRECT,
ANTICIPATED_DIRECT_AMOUNT=r_amount_upd.ANTICIPATED_CHANGE_DIRECT,
ANTICIPATED_INDIRECT_AMOUNT=r_amount_upd.ANTICIPATED_CHANGE_INDIRECT
WHERE AWARD_NUMBER=ls_award_number
AND SEQUENCE_NUMBER=r_amount_upd.SEQUENCE_NUMBER;

UPDATE AWARD_AMOUNT_INFO
SET ANTICIPATED_CHANGE_DIRECT=r_amount_upd.ANTICIPATED_CHANGE_DIRECT,
ANTICIPATED_CHANGE_INDIRECT=r_amount_upd.ANTICIPATED_CHANGE_INDIRECT,
ANTICIPATED_TOTAL_DIRECT=r_amount_upd.ANTICIPATED_TOTAL_DIRECT,
ANTICIPATED_TOTAL_INDIRECT=r_amount_upd.ANTICIPATED_TOTAL_INDIRECT,
OBLIGATED_TOTAL_DIRECT=r_amount_upd.OBLIGATED_TOTAL_DIRECT,
OBLIGATED_TOTAL_INDIRECT=r_amount_upd.OBLIGATED_TOTAL_INDIRECT,
ANTICIPATED_TOTAL_AMOUNT=r_amount_upd.ANTICIPATED_TOTAL_AMOUNT,
ANT_DISTRIBUTABLE_AMOUNT=r_amount_upd.ANT_DISTRIBUTABLE_AMOUNT,
FINAL_EXPIRATION_DATE=r_amount_upd.FINAL_EXPIRATION_DATE,
CURRENT_FUND_EFFECTIVE_DATE=r_amount_upd.CURRENT_FUND_EFFECTIVE_DATE,
AMOUNT_OBLIGATED_TO_DATE=r_amount_upd.AMOUNT_OBLIGATED_TO_DATE,
OBLI_DISTRIBUTABLE_AMOUNT=r_amount_upd.OBLI_DISTRIBUTABLE_AMOUNT,
OBLIGATION_EXPIRATION_DATE=r_amount_upd.OBLIGATION_EXPIRATION_DATE,
ENTRY_TYPE=r_amount_upd.ENTRY_TYPE,
EOM_PROCESS_FLAG=r_amount_upd.EOM_PROCESS_FLAG,
UPDATE_TIMESTAMP=r_amount_upd.UPDATE_TIMESTAMP,
UPDATE_USER=r_amount_upd.UPDATE_USER,
ANTICIPATED_CHANGE=r_amount_upd.ANTICIPATED_CHANGE,
OBLIGATED_CHANGE=r_amount_upd.OBLIGATED_CHANGE,
OBLIGATED_CHANGE_DIRECT=r_amount_upd.OBLIGATED_CHANGE_DIRECT,
OBLIGATED_CHANGE_INDIRECT=r_amount_upd.OBLIGATED_CHANGE_INDIRECT
WHERE AWARD_NUMBER=ls_award_number
AND SEQUENCE_NUMBER=r_amount_upd.SEQUENCE_NUMBER;

END LOOP;
CLOSE c_amount_upd;
END;
/
select ' End time of UPDATE_AWARD_AMOUNT_INFO is '|| localtimestamp from dual
/