
INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL, 1078, 1207, 	'N',	'Current space insufficient:', 	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL, 1078, 1209, 	'N',	'Current space insufficient:', 	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1079,	1207,	'Y',	'Use of space other than submitting unit:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1079,	1209,	'Y',	'Use of space other than submitting unit:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1080,	1207,	'Y',	'Will appoint individuals outside submitting unit:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1080,	1209,	'Y',	'Will appoint individuals outside submitting unit:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1081,	1207,	'Y',	'Will appoint visitors at MIT:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1081,	1209,	'Y',	'Will appoint visitors at MIT:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1088,	1207,	'Y',	'Use of animals:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1088,	1209,	'Y',	'Use of animals:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1089,	1207,	'Y',	'Use of human subjects:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1089,	1209,	'Y',	'Use of human subjects:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1085,	1207,	'Y',	'Restricted access or use for some researchers:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1085,	1209,	'Y',	'Restricted access or use for some researchers:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1086,	1207,	'Y',	'Part of project performed outside US:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1086,	1209,	'Y',	'Part of project performed outside US:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1087,	1207,	'Y',	'Will ship outside the US:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1087,	1209,	'Y',	'Will ship outside the US:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1082,	1207,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1082,	1209,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1082,	1208,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1083,	1207,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1083,	1209,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1083,	1208,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1084,	1207,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1084,	1209,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1084,	1208,	'Y',	'Related SFI Identified:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1091,	1207,	'Y',	'Lobbying:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1091,	1209,	'Y',	'Lobbying:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1092,	1207,	'Y',	'Potential Debarment Issue:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1092,	1209,	'Y',	'Potential Debarment Issue:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1090,	1207,	'N',	'Will not certify proposal information:',	'admin')
/

INSERT INTO PROP_QUESTIONNAIRE_VALIDATION (QUESTIONNAIRE_VALIDATION_ID, QUESTION_ID, QUESTIONNAIRE_ID, ANSWER, VALIDATION_MESSAGE, UPDATE_USER)
VALUES(SEQ_QUESTIONNAIRE_VAL_ID.NEXTVAL,	1093,	1209,	'N',	'Will not certify proposal information:',	'admin')
/
