insert into ROLODEX(ROLODEX_ID,LAST_NAME,FIRST_NAME,MIDDLE_NAME,SUFFIX,PREFIX,TITLE,ORGANIZATION,ADDRESS_LINE_1,ADDRESS_LINE_2,ADDRESS_LINE_3,FAX_NUMBER,EMAIL_ADDRESS,CITY,COUNTY,STATE,POSTAL_CODE,COMMENTS,PHONE_NUMBER,COUNTRY_CODE,SPONSOR_CODE,OWNED_BY_UNIT,SPONSOR_ADDRESS_FLAG,DELETE_FLAG,CREATE_USER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID)
select cr.ROLODEX_ID,cr.LAST_NAME,cr.FIRST_NAME,cr.MIDDLE_NAME,cr.SUFFIX,cr.PREFIX,cr.TITLE,cr.ORGANIZATION,cr.ADDRESS_LINE_1,cr.ADDRESS_LINE_2,cr.ADDRESS_LINE_3,cr.FAX_NUMBER,cr.EMAIL_ADDRESS,cr.CITY,cr.COUNTY,cr.STATE,cr.POSTAL_CODE,cr.COMMENTS,cr.PHONE_NUMBER,cr.COUNTRY_CODE,cr.SPONSOR_CODE,cr.OWNED_BY_UNIT,cr.SPONSOR_ADDRESS_FLAG,cr.DELETE_FLAG,cr.CREATE_USER,cr.UPDATE_TIMESTAMP,cr.UPDATE_USER,1,sys_guid()
from OSP$ROLODEX@coeus.kuali cr left outer join ROLODEX r on cr.ROLODEX_ID=r.ROLODEX_ID where r.ROLODEX_ID is null
/
insert into SPONSOR(SPONSOR_CODE,SPONSOR_NAME,ACRONYM,SPONSOR_TYPE_CODE,DUN_AND_BRADSTREET_NUMBER,DUNS_PLUS_FOUR_NUMBER,DODAC_NUMBER,CAGE_NUMBER,POSTAL_CODE,STATE,COUNTRY_CODE,ROLODEX_ID,AUDIT_REPORT_SENT_FOR_FY,OWNED_BY_UNIT,CREATE_USER,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,ACTV_IND)
select s.SPONSOR_CODE,s.SPONSOR_NAME,s.ACRONYM,s.SPONSOR_TYPE_CODE,s.DUN_AND_BRADSTREET_NUMBER,s.DUNS_PLUS_FOUR_NUMBER,s.DODAC_NUMBER,s.CAGE_NUMBER,s.POSTAL_CODE,s.STATE,s.COUNTRY_CODE,s.ROLODEX_ID,s.AUDIT_REPORT_SENT_FOR_FY,s.OWNED_BY_UNIT,s.CREATE_USER,s.UPDATE_TIMESTAMP,s.UPDATE_USER,1,sys_guid(),decode( upper(s.STATUS),'A','Y','N' )
from OSP$SPONSOR@coeus.kuali  s left outer join SPONSOR os on s.SPONSOR_CODE=os.SPONSOR_CODE where  os.SPONSOR_CODE is null
/
insert into INV_CREDIT_TYPE(INV_CREDIT_TYPE_CODE,DESCRIPTION,ADDS_TO_HUNDRED,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,ACTIVE_FLAG,OBJ_ID)
select i.INV_CREDIT_TYPE_CODE,i.DESCRIPTION,i.ADDS_TO_HUNDRED,i.UPDATE_TIMESTAMP,i.UPDATE_USER,1,'Y',sys_guid() 
from OSP$INV_CREDIT_TYPE@coeus.kuali i left outer join INV_CREDIT_TYPE ki on i.INV_CREDIT_TYPE_CODE=ki.INV_CREDIT_TYPE_CODE where  ki.INV_CREDIT_TYPE_CODE is null
/
INSERT INTO UNIT(UNIT_NUMBER,UNIT_NAME,ORGANIZATION_ID,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,PARENT_UNIT_NUMBER,OBJ_ID,ACTIVE_FLAG)
SELECT u.UNIT_NUMBER,u.UNIT_NAME,u.ORGANIZATION_ID,u.UPDATE_TIMESTAMP,u.UPDATE_USER,1,uh.PARENT_UNIT_NUMBER,sys_guid(),'Y' 
FROM OSP$UNIT@coeus.kuali u INNER JOIN OSP$UNIT_HIERARCHY@coeus.kuali uh ON u.UNIT_NUMBER=uh.UNIT_NUMBER
LEFT OUTER JOIN UNIT ku ON u.UNIT_NUMBER=ku.UNIT_NUMBER WHERE ku.UNIT_NUMBER IS NULL
/
commit
/