insert into KCSO.COEUS_SUB_MODULE (COEUS_SUB_MODULE_ID,MODULE_CODE,SUB_MODULE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,REQUIRE_UNIQUE_QUESTIONNAIRE)
values(26,3,4,'Proposal Person PI Certification',sysdate,'admin',1,SYS_GUID(),'N');
/
insert into KCSO.COEUS_SUB_MODULE (COEUS_SUB_MODULE_ID,MODULE_CODE,SUB_MODULE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,REQUIRE_UNIQUE_QUESTIONNAIRE)
values(27,3,5,'Proposal Person COI Certification',sysdate,'admin',1,SYS_GUID(),'N');
/
insert into KCSO.COEUS_SUB_MODULE (COEUS_SUB_MODULE_ID,MODULE_CODE,SUB_MODULE_CODE,DESCRIPTION,UPDATE_TIMESTAMP,UPDATE_USER,VER_NBR,OBJ_ID,REQUIRE_UNIQUE_QUESTIONNAIRE)
values(28,3,6,'Proposal Person KP Certification',sysdate,'admin',1,SYS_GUID(),'N');
/