CREATE SEQUENCE  SEQ_SAP_BATCH_ID  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE
/
CREATE SEQUENCE SEQ_ROLO_FEED_ID
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  /  
  CREATE SEQUENCE SEQ_SAP_ID
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  /   
  CREATE SEQUENCE SEQ_SAP_FEED_BATCH_ID
  START WITH 1
  MAXVALUE 9999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER
  /
 CREATE SEQUENCE  SEQ_SPON_BATCH_ID  
  MINVALUE 1 
  MAXVALUE 999 
  INCREMENT BY 1 
  START WITH 1 
  NOCACHE  
  NOORDER  
  CYCLE
  /  
  CREATE TABLE TEMP_SAP_SPON_CD  (
  "SPONSOR_CODE" CHAR(6 BYTE), 
	"SPONSOR_NAME" VARCHAR2(60 BYTE), 
	"ADMIN_ACTIVITY_CODE" CHAR(2 BYTE),
   "UPDATE_TIMESTAMP" DATE, 
	"UPDATE_USER" VARCHAR2(60 BYTE), 
	"VER_NBR" NUMBER(8,0) DEFAULT 1, 
	"OBJ_ID" VARCHAR2(36 BYTE) NOT NULL ENABLE)
/	
 CREATE TABLE SAP_FEED
   (SAP_FEED_ID NUMBER(12,0) NOT NULL ENABLE,	
   "BATCH_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"FEED_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SAP_TRANSACTION" CHAR(4 BYTE) NOT NULL ENABLE, 
	"WBS_TYPE" CHAR(1 BYTE) NOT NULL ENABLE, 
	"ACCOUNT_LEVEL" CHAR(1 BYTE) NOT NULL ENABLE, 
	"MIT_SAP_ACCOUNT" CHAR(12 BYTE) NOT NULL ENABLE, 
	"DEPTNO" CHAR(7 BYTE) NOT NULL ENABLE, 
	"BILLING_ELEMENT" CHAR(1 BYTE), 
	"BILLING_TYPE" CHAR(2 BYTE), 
	"BILLING_FORM" CHAR(2 BYTE), 
	"SPON_CODE" CHAR(6 BYTE), 
	"PRIMARY_SPONSOR" CHAR(6 BYTE), 
	"CONTRACT" CHAR(70 BYTE), 
	"CUSTOMER" CHAR(10 BYTE), 
	"TERM_CODE" CHAR(1 BYTE), 
	"PARENT_ACCOUNT" CHAR(12 BYTE) NOT NULL ENABLE, 
	"ACCTNAME" CHAR(60 BYTE), 
	"EFFECT_DATE" CHAR(8 BYTE), 
	"EXPIRATION" CHAR(8 BYTE), 
	"SUB_PLAN" CHAR(1 BYTE), 
	"MAIL_CODE" CHAR(1 BYTE), 
	"SUPERVISOR" CHAR(9 BYTE), 
	"SUPER_ROOM" CHAR(10 BYTE), 
	"ADDRESSEE" CHAR(9 BYTE), 
	"ADDR_ROOM" CHAR(10 BYTE), 
	"AGREE_TYPE" CHAR(2 BYTE), 
	"AUTH_TOTAL" CHAR(12 BYTE), 
	"COST_SHARE" CHAR(1 BYTE), 
	"FUND_CLASS" CHAR(3 BYTE), 
	"POOL_CODE" CHAR(1 BYTE), 
	"PENDING_CODE" CHAR(1 BYTE), 
	"FS_CODE" CHAR(1 BYTE), 
	"DFAFS" CHAR(20 BYTE), 
	"CALC_CODE" CHAR(1 BYTE), 
	"CFDANO" CHAR(7 BYTE), 
	"COSTING_SHEET_KEY" CHAR(6 BYTE), 
	"LAB_ALLOCATION_KEY" CHAR(6 BYTE), 
	"EB_ADJUSTMENT_KEY" CHAR(6 BYTE), 
	"OH_ADJUSTMENT_KEY" CHAR(6 BYTE), 
	"COMMENT1" CHAR(60 BYTE), 
	"COMMENT2" CHAR(60 BYTE), 
	"COMMENT3" CHAR(60 BYTE), 
	"TITLE" CHAR(150 BYTE), 
	"SORT_ID" NUMBER(6,0),
  "UPDATE_USER" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
	"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
  "VER_NBR" NUMBER(8,0) NOT NULL ENABLE, 
	"OBJ_ID" VARCHAR2(36 BYTE) NOT NULL ENABLE,
  CONSTRAINT "PK_SAP_FEED" PRIMARY KEY ("SAP_FEED_ID"),
  CONSTRAINT "UQ_SAP_FEED" UNIQUE  ("BATCH_ID", "FEED_ID"))
  /  
   CREATE TABLE SAP_FEED_BATCH_LIST 
	(	SAP_FEED_BATCH_ID NUMBER(12,0) NOT NULL ENABLE,
  "BATCH_ID" NUMBER(3,0) NOT NULL ENABLE, 
		"BATCH_FILE_NAME" CHAR(27 BYTE) NOT NULL ENABLE, 
		"BATCH_TIMESTAMP" DATE NOT NULL ENABLE, 
		"UPDATE_USER" VARCHAR2(8 BYTE) NOT NULL ENABLE, 
		"NO_OF_RECORDS" NUMBER(5,0) NOT NULL ENABLE,
		"UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
		"VER_NBR" NUMBER(8,0) NOT NULL ENABLE, 
		"OBJ_ID" VARCHAR2(36 BYTE) NOT NULL ENABLE,
		CONSTRAINT "UQ_BATCH_LIST" UNIQUE ("BATCH_ID"),
    CONSTRAINT "PK_SAP_FEED_BATCH_LIST" PRIMARY KEY ("SAP_FEED_BATCH_ID"))
	/	
	 CREATE TABLE SAP_FEED_ERROR_LOG
   (	"BATCH_ID" NUMBER(3,0) NOT NULL ENABLE, 
	"FEED_ID" NUMBER(10,0) NOT NULL ENABLE, 
	"ERROR_MESSAGE" VARCHAR2(350 BYTE),
  "UPDATE_TIMESTAMP" DATE NOT NULL ENABLE, 
  "VER_NBR" NUMBER(8,0) NOT NULL ENABLE, 
	"OBJ_ID" VARCHAR2(36 BYTE) NOT NULL ENABLE,
  "UPDATE_USER" VARCHAR2(8 BYTE) NOT NULL ENABLE)
  /