Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Aggregator','Aggregator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Application Administrator','Application Administrator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Award Budget Administrator','Award Budget Administrator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Award Budget Aggregator','Award Budget Aggregator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Budget Creator','Budget Creator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Create Temporary Proposal Log','Create Temporary Proposal Log',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('IACUC Administrator','IACUC Administrator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('IACUC Protocol Aggregator','IACUC Protocol Aggregator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('IACUC Protocol Creator','IACUC Protocol Creator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('IACUC Protocol Viewer','IACUC Protocol Viewer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('IACUC Reviewer','IACUC Reviewer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('IP Review Maintainer','IP Review Maintainer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('IRB Administrator','IRB Administrator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('IRB Reviewer','IRB Reviewer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Maintain Custom Reports','Maintain Custom Reports',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Maintain Questionnaire','Maintain Questionnaire',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Modify All Dev Proposals','Modify All Dev Proposals',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Modify Training','Modify Training',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Narrative Writer','Narrative Writer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('OSP Administrator','OSP Administrator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('OSP Administrator','Kuali Rules Management System Administrator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Proposal Creator','Proposal Creator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Proposal Submission','Proposal Submission',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Protocol Aggregator','Protocol Aggregator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Protocol Creator','Protocol Creator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Protocol Viewer','Protocol Viewer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Role Maintenance','Role Maintenance',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Run Award Reports','Run Award Reports',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Run Committee Reports','Run Committee Reports',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Run Dev Proposal Reports','Run Dev Proposal Reports',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Run Global Reports','Run Global Reports',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Run Person Reports','Run Person Reports',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Run Protocol Reports','Run Protocol Reports',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Run Rolodex Reports','Run Rolodex Reports',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Run Sponsor Reports','Run Sponsor Reports',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Run Unit Reports','Run Unit Reports',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Run User Reports','Run User Reports',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Sponsor Maintainer','Sponsor Maintainer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('View All Dev Proposals','View All Dev Proposals',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('View all IACUC Protocols','View all IACUC Protocols',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('View Proposal Log','View Proposal Log',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Viewer','Viewer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Delete Any Protocol','Protocol Deleter',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('IACUC Protocol Approver','IACUC ProtocolApprover',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('IP Review Maintainer','Institutional Proposal Maintainer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Maintain Award Budget','Award Budget Maintainer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Access Institutionally Maintained Salaries','View Institutionally Maintained Salaries',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Access Proposal Person Institutional Salaries','Access_Proposal_Person_Institutional_Salaries',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Approve Award Budget','Award Budget Approver',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Modify Award','Award Modifier',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Modify Award','Time And Money Modifier',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Modify Award Budget','Award Budget Modifier',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Negotiation SuperUser','Negotiation Administrator',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Protocol Approver','ProtocolApprover',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Run Budget Reports','Run Dev Budget Reports',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('View Award Budget','Award Budget Viewer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('View Institute Proposal Document','Institutional Proposal Viewer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('View Subcontract','View Subaward',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('View Template','Template Viewer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Modify Subcontract','Modify Subaward',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Maintain Conflict of Interest','COI Maintainer',null);
Insert into KC_COEUS_ROLE_MAPPING (COEUS_ROLES,KC_ROLES,IS_INSERTED) values ('Rolodex Maintainer','Address Book Maintainer',null);
INSERT INTO KC_COEUS_ROLE_MAPPING (COEUS_ROLES, KC_ROLES) VALUES ('Modify Negotiations', 'Negotiation Creator');
commit
/